// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: message2.proto

package message2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchRequestCommonStar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *FetchRequestCommonStar) Reset() {
	*x = FetchRequestCommonStar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchRequestCommonStar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequestCommonStar) ProtoMessage() {}

func (x *FetchRequestCommonStar) ProtoReflect() protoreflect.Message {
	mi := &file_message2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequestCommonStar.ProtoReflect.Descriptor instead.
func (*FetchRequestCommonStar) Descriptor() ([]byte, []int) {
	return file_message2_proto_rawDescGZIP(), []int{0}
}

func (x *FetchRequestCommonStar) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

//订单信息 repeated User user = 1;
type FriendsResponseCommonStars struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonPersonList []string `protobuf:"bytes,1,rep,name=CommonPersonList,proto3" json:"CommonPersonList,omitempty"`
	StarPersonList   []string `protobuf:"bytes,2,rep,name=StarPersonList,proto3" json:"StarPersonList,omitempty"`
}

func (x *FriendsResponseCommonStars) Reset() {
	*x = FriendsResponseCommonStars{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendsResponseCommonStars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendsResponseCommonStars) ProtoMessage() {}

func (x *FriendsResponseCommonStars) ProtoReflect() protoreflect.Message {
	mi := &file_message2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendsResponseCommonStars.ProtoReflect.Descriptor instead.
func (*FriendsResponseCommonStars) Descriptor() ([]byte, []int) {
	return file_message2_proto_rawDescGZIP(), []int{1}
}

func (x *FriendsResponseCommonStars) GetCommonPersonList() []string {
	if x != nil {
		return x.CommonPersonList
	}
	return nil
}

func (x *FriendsResponseCommonStars) GetStarPersonList() []string {
	if x != nil {
		return x.StarPersonList
	}
	return nil
}

var File_message2_proto protoreflect.FileDescriptor

var file_message2_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x30, 0x0a, 0x16, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x70, 0x0a, 0x1a, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x10, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x72, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x53,
	0x74, 0x61, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x32, 0x8e, 0x01,
	0x0a, 0x1b, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x53, 0x68, 0x69, 0x70, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6f, 0x0a,
	0x27, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x50, 0x6c, 0x75, 0x73, 0x43,
	0x65, 0x6c, 0x65, 0x62, 0x72, 0x69, 0x74, 0x79, 0x12, 0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x1a, 0x23, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x73, 0x42, 0x0d,
	0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message2_proto_rawDescOnce sync.Once
	file_message2_proto_rawDescData = file_message2_proto_rawDesc
)

func file_message2_proto_rawDescGZIP() []byte {
	file_message2_proto_rawDescOnce.Do(func() {
		file_message2_proto_rawDescData = protoimpl.X.CompressGZIP(file_message2_proto_rawDescData)
	})
	return file_message2_proto_rawDescData
}

var file_message2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message2_proto_goTypes = []interface{}{
	(*FetchRequestCommonStar)(nil),     // 0: message.FetchRequestCommonStar
	(*FriendsResponseCommonStars)(nil), // 1: message.FriendsResponseCommonStars
}
var file_message2_proto_depIdxs = []int32{
	0, // 0: message.FriendShipCommonStarService.GetFriendsListCommonPersonPlusCelebrity:input_type -> message.FetchRequestCommonStar
	1, // 1: message.FriendShipCommonStarService.GetFriendsListCommonPersonPlusCelebrity:output_type -> message.FriendsResponseCommonStars
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message2_proto_init() }
func file_message2_proto_init() {
	if File_message2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchRequestCommonStar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendsResponseCommonStars); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message2_proto_goTypes,
		DependencyIndexes: file_message2_proto_depIdxs,
		MessageInfos:      file_message2_proto_msgTypes,
	}.Build()
	File_message2_proto = out.File
	file_message2_proto_rawDesc = nil
	file_message2_proto_goTypes = nil
	file_message2_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FriendShipCommonStarServiceClient is the client API for FriendShipCommonStarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FriendShipCommonStarServiceClient interface {
	GetFriendsListCommonPersonPlusCelebrity(ctx context.Context, in *FetchRequestCommonStar, opts ...grpc.CallOption) (*FriendsResponseCommonStars, error)
}

type friendShipCommonStarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendShipCommonStarServiceClient(cc grpc.ClientConnInterface) FriendShipCommonStarServiceClient {
	return &friendShipCommonStarServiceClient{cc}
}

func (c *friendShipCommonStarServiceClient) GetFriendsListCommonPersonPlusCelebrity(ctx context.Context, in *FetchRequestCommonStar, opts ...grpc.CallOption) (*FriendsResponseCommonStars, error) {
	out := new(FriendsResponseCommonStars)
	err := c.cc.Invoke(ctx, "/message.FriendShipCommonStarService/GetFriendsListCommonPersonPlusCelebrity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FriendShipCommonStarServiceServer is the server API for FriendShipCommonStarService service.
type FriendShipCommonStarServiceServer interface {
	GetFriendsListCommonPersonPlusCelebrity(context.Context, *FetchRequestCommonStar) (*FriendsResponseCommonStars, error)
}

// UnimplementedFriendShipCommonStarServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFriendShipCommonStarServiceServer struct {
}

func (*UnimplementedFriendShipCommonStarServiceServer) GetFriendsListCommonPersonPlusCelebrity(context.Context, *FetchRequestCommonStar) (*FriendsResponseCommonStars, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFriendsListCommonPersonPlusCelebrity not implemented")
}

func RegisterFriendShipCommonStarServiceServer(s *grpc.Server, srv FriendShipCommonStarServiceServer) {
	s.RegisterService(&_FriendShipCommonStarService_serviceDesc, srv)
}

func _FriendShipCommonStarService_GetFriendsListCommonPersonPlusCelebrity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequestCommonStar)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendShipCommonStarServiceServer).GetFriendsListCommonPersonPlusCelebrity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.FriendShipCommonStarService/GetFriendsListCommonPersonPlusCelebrity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendShipCommonStarServiceServer).GetFriendsListCommonPersonPlusCelebrity(ctx, req.(*FetchRequestCommonStar))
	}
	return interceptor(ctx, in, info, handler)
}

var _FriendShipCommonStarService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.FriendShipCommonStarService",
	HandlerType: (*FriendShipCommonStarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFriendsListCommonPersonPlusCelebrity",
			Handler:    _FriendShipCommonStarService_GetFriendsListCommonPersonPlusCelebrity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message2.proto",
}
